spring:
   application:
     name: "social-security-service"

server:
   port: 8082
   
# Expose all the actuator end points
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: "always"

